name: build

on:
  workflow_dispatch:

jobs:
  build: 
    runs-on: "ubuntu-latest"

    steps:
      - task: UseNode@1
        inputs:
          version: "16.x"
        displayName: "Install Node.js"

      - script: npm install
        workingDirectory: "./src/client"
        displayName: "Install node modules"

      - script: npm run build install
        workingDirectory: "./src/client"
        displayName: "Install node modules"
