name: cd

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Unzip Artifact
        run: |
          cd build
          unzip build-artifacts.zip
          ls -la dist

      - name: Show current directory and contents
        run: |
          echo "Current directory:"
          pwd
          echo "Listing all contents:"
          ls -R

      - name: Deploy to Azure Storage
        run: |
          # Enable static website (only needs to be done once)
          az storage blob service-properties update \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --static-website \
            --index-document index.html \
            --404-document index.html

          # Upload entire dist folder to the $web container
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source build/dist \
            --pattern '*' \
            --overwrite true
