name: Pull Request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  id-token: write
  security-events: write
  statuses: write

concurrency:
  group: ${{ format('pr{0}', github.event.number) }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_CSHARP: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/build.yml
    with:
      retention_days: 1
    secrets: inherit