name: pull request

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  id-token: write
  security-events: write
  statuses: write

concurrency:
  group: ${{ format('pr{0}', github.event.number) }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd src/client
          npm install
      - name: Run ESLint
        run: |
          cd src/client
          npx eslint . --ext .js,.ts
      - uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_CSHARP: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  security:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd src/client
          npm install
      - name: Run npm audit
        run: |
          cd src/client
          npm audit --production
